// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCesM3I8vVWmQvH7DnqRLOkAqj1CrbwMK4',
    appId: '1:547090704053:web:41d34362e713a2506800fc',
    messagingSenderId: '547090704053',
    projectId: 'zenhub-9ac68',
    authDomain: 'zenhub-9ac68.firebaseapp.com',
    storageBucket: 'zenhub-9ac68.appspot.com',
    measurementId: 'G-K5JZ9VR4DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOthW1HDu3XadpcB3Cr7EAjnxSgDR334',
    appId: '1:547090704053:android:aac9a99ae911742d6800fc',
    messagingSenderId: '547090704053',
    projectId: 'zenhub-9ac68',
    storageBucket: 'zenhub-9ac68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr1Y1V1vzk7nqHnXjyYlsY597dX9fxJkU',
    appId: '1:547090704053:ios:5db553b59b289bfa6800fc',
    messagingSenderId: '547090704053',
    projectId: 'zenhub-9ac68',
    storageBucket: 'zenhub-9ac68.appspot.com',
    iosBundleId: 'com.example.zenhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr1Y1V1vzk7nqHnXjyYlsY597dX9fxJkU',
    appId: '1:547090704053:ios:5db553b59b289bfa6800fc',
    messagingSenderId: '547090704053',
    projectId: 'zenhub-9ac68',
    storageBucket: 'zenhub-9ac68.appspot.com',
    iosBundleId: 'com.example.zenhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCesM3I8vVWmQvH7DnqRLOkAqj1CrbwMK4',
    appId: '1:547090704053:web:934a54098a8c6d7d6800fc',
    messagingSenderId: '547090704053',
    projectId: 'zenhub-9ac68',
    authDomain: 'zenhub-9ac68.firebaseapp.com',
    storageBucket: 'zenhub-9ac68.appspot.com',
    measurementId: 'G-PQN39N6PFJ',
  );
}
